anek:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080

server:
  port: 8080
#  servlet:
#    context-path: /v1/schedule
spring:
  application:
    name: Schedule
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Swagger Configuration
springdoc:
  swagger-ui:
    tryItOutEnabled: true





#  patch:
#    summary: Exemplo de endpoint que aceita um Map<String, Object>
#    requestBody:
#      required: true
#      content:
#        application/json:
#          schema:
#            type: object
#            properties:
#              dados:
#                type: object
#                additionalProperties:
#                  type: string  # Você pode ajustar o tipo conforme necessário
#    responses:
#      '200':
#        description: Sucesso
#      '400':
#        description: Requisição inválida

